[project]
name = "multi-tenant-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beanie>=2.0.0",
    "fastapi[standard]>=0.116.2",
    "pymongo>=4.15.1",
    "python-dotenv>=1.1.1",
]
